apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-web
  namespace: erpnext-dev
  labels:
    app: erpnext
    component: web
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erpnext
      component: web
  template:
    metadata:
      labels:
        app: erpnext
        component: web
    spec:

      containers:
      - name: web
        image: ghcr.io/ayoubdahir/erpnext-custom:latest
        command: ["/bin/bash", "-c"]
        args:
        - >-
            /home/frappe/frappe-bench/env/bin/pip install -e apps/healthcare &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/his &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/hrms &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/insights &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/rasiin_design &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/rasiin_hr &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/frappe_whatsapp &&
            bench start
        env:
        - name: FRAPPE_SITE_NAME
          value: dev.erp.local
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        - name: REDIS_CACHE
          value: redis://redis:6379/0
        - name: REDIS_QUEUE
          value: redis://redis:6379/1
        - name: REDIS_SOCKETIO
          value: redis://redis:6379/2
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: erpnext-pvc
