apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-scheduler
  namespace: erpnext-dev
  labels:
    app: erpnext
    component: scheduler
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erpnext
      component: scheduler
  template:
    metadata:
      labels:
        app: erpnext
        environment: dev
        component: scheduler
    spec:
      initContainers:
      - name: populate-sites
        image: ghcr.io/ayoubdahir/erpnext-custom:latest
        securityContext:
          runAsUser: 0
        command: ["bash", "-c"]
        env:
        - name: REDIS_CACHE
          value: redis://redis:6379/0
        - name: REDIS_QUEUE
          value: redis://redis:6379/1
        - name: REDIS_SOCKETIO
          value: redis://redis:6379/2
        args:
        - |
          echo "Checking sites..."
          if [ ! -f /sites-pvc/common_site_config.json ]; then
            echo "Populating sites volume..."
            cp -R /home/frappe/frappe-bench/sites/* /sites-pvc/
            chown -R 1000:1000 /sites-pvc
          fi
          
          echo "Patching Redis URLs in common_site_config.json..."
          python3 -c "import json, os; p='/sites-pvc/common_site_config.json'; d=json.load(open(p)); d.update({'redis_cache': os.environ['REDIS_CACHE'], 'redis_queue': os.environ['REDIS_QUEUE'], 'redis_socketio': os.environ['REDIS_SOCKETIO']}); json.dump(d, open(p,'w'), indent=2)"
          echo "Patch Complete."
        volumeMounts:
        - name: sites
          mountPath: /sites-pvc
      containers:
      - name: scheduler
        image: ghcr.io/ayoubdahir/erpnext-custom:latest
        command: ["bench", "schedule"]

        env:
        - name: FRAPPE_SITE_NAME
          value: dev.erp.local
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        - name: REDIS_CACHE
          value: redis://redis:6379/0
        - name: REDIS_QUEUE
          value: redis://redis:6379/1
        - name: REDIS_SOCKETIO
          value: redis://redis:6379/2
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: erpnext-pvc