apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext
  namespace: erpnext-production
  labels:
    app: erpnext
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erpnext
      environment: production
  template:
    metadata:
      labels:
        app: erpnext
        environment: production
    spec:
      initContainers:
      - name: populate-sites-volume
        image: ghcr.io/ayoubdahir/erpnext-custom:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Initializing sites volume..."
            if [ -z "$(ls -A /sites-pvc)" ]; then
               echo "Copying sites..."
               cp -R /home/frappe/frappe-bench/sites/* /sites-pvc/
               chown -R frappe:frappe /sites-pvc
            else
               echo "Sites volume already populated."
            fi
        volumeMounts:
        - name: sites
          mountPath: /sites-pvc
      containers:
      - name: erpnext
        image: ghcr.io/ayoubdahir/erpnext-custom:latest
        command: ["/bin/bash", "-c"]
        args:
          - >-
            /home/frappe/frappe-bench/env/bin/pip install -e apps/healthcare &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/his &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/hrms &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/insights &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/rasiin_design &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/rasiin_hr &&
            /home/frappe/frappe-bench/env/bin/pip install -e apps/frappe_whatsapp &&
            bench start
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: socketio
        env:
        - name: FRAPPE_SITE_NAME
          value: production.erp.local
        - name: DB_HOST
          value: "mariadb"
        - name: DB_PORT
          value: "3306"
        - name: REDIS_CACHE
          value: redis://redis:6379/0
        - name: REDIS_QUEUE
          value: redis://redis:6379/1
        - name: REDIS_SOCKETIO
          value: redis://redis:6379/2
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: erpnext-sites
